"""Add play_addr field to Trend model

Revision ID: 6225f6e36342
Revises: e8f7a9c2b1d3
Create Date: 2026-02-07 01:36:45.829576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6225f6e36342'
down_revision: Union[str, None] = 'e8f7a9c2b1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('play_addr', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'play_addr')
    # ### end Alembic commands ###
